/**
 * `findCandidates` — which stored leads could this business already be?
 *
 * Comparing every record against every other record is quadratic and, at
 * nationwide scale, not a thing that finishes. So candidates are generated by
 * **blocking**: only leads that share something cheap and indexed are ever
 * scored. The blocks are exactly the dedup signals, plus one fuzzy block for the
 * rule that has no exact key:
 *
 * | Block                | Index                          | Finds                        |
 * | -------------------- | ------------------------------ | ---------------------------- |
 * | each phone           | `lead_phones_e164_idx`         | rule 1                       |
 * | each website domain  | `lead_contacts_domain_idx`     | rule 2                       |
 * | each email           | `lead_contacts_kind_value_idx` | rule 3                       |
 * | registration number  | `leads_registration_idx`       | the state's key              |
 * | exact name key       | `leads_name_idx`               | rule 4, exact spelling       |
 * | every lead in a city | `leads_city_idx`               | rule 4, near-duplicate names |
 * | each social profile  | `lead_contacts_kind_value_idx` | corroboration                |
 *
 * The city block is the only one that can be large, and it is the one that has
 * to exist: a near-duplicate name has no exact key to look up, and comparing
 * only inside one city is both the correct rule and what keeps the work bounded.
 * When a city block is bigger than `MAX_CITY_BLOCK` the pass stops and *says so*
 * — a silent cap would read as "no duplicates here".
 */
import type { Db } from '../db/client.js';
import {
  activeLeads,
  findAllByContact,
  findAllByDomain,
  findAllByEmail,
  findAllByNameKey,
  findAllByPhone,
  findAllByRegistrationNumber,
  findLeadsInCity,
} from '../db/repo.js';
import { MAX_CITY_BLOCK } from './weights.js';
import { requireLeadRecord, toLeadRecord } from './from-db.js';
import { scoreMatch } from './score.js';
import { STRUCTURAL_QUARANTINE } from './quarantine.js';
import type { LeadRecord, MatchCandidate, MatchScore, Quarantine } from './types.js';

export interface FindCandidatesOptions {
  readonly quarantine?: Quarantine | undefined;
  /** Drop `distinct` verdicts. On by default — a caller wants matches, not a census. */
  readonly includeDistinct?: boolean | undefined;
  /**
   * Skip the city-wide fuzzy block. The exact blocks alone are what an insert
   * needs; the fuzzy pass is for the sweep.
   */
  readonly exactOnly?: boolean | undefined;
  /** Counter for city blocks that hit `MAX_CITY_BLOCK`. The sweep reports it. */
  readonly onBlockTruncated?: ((cityId: string, size: number) => void) | undefined;
}

/**
 * Every stored lead that could be the same business as `record`, scored and
 * ordered strongest first.
 *
 * `record.id`, when set, is excluded — a lead is not its own duplicate.
 */
export function findCandidates(
  db: Db,
  record: LeadRecord,
  options: FindCandidatesOptions = {},
): MatchCandidate[] {
  const quarantine = options.quarantine ?? STRUCTURAL_QUARANTINE;
  const blocked = new Set<number>(record.id == null ? [] : [record.id]);
  const candidateIds = new Set<number>();

  const collect = (ids: readonly number[]): void => {
    for (const id of ids) if (!blocked.has(id)) candidateIds.add(id);
  };

  for (const phone of record.phones) {
    if (quarantine.has('phone', phone)) continue;
    collect(findAllByPhone(db, phone).map((lead) => lead.id));
  }
  for (const domain of record.websiteDomains) {
    if (quarantine.has('website_domain', domain)) continue;
    collect(findAllByDomain(db, domain).map((lead) => lead.id));
  }
  for (const email of record.emails) {
    if (quarantine.has('email', email)) continue;
    collect(findAllByEmail(db, email).map((lead) => lead.id));
  }
  if (record.registrationNumber) {
    collect(findAllByRegistrationNumber(db, record.registrationNumber).map((lead) => lead.id));
  }
  for (const profile of record.socialUrls) {
    for (const kind of ['facebook', 'instagram', 'google_maps'] as const) {
      collect(findAllByContact(db, kind, profile).map((lead) => lead.id));
    }
  }
  if (record.nameKey.ascii !== '') {
    collect(findAllByNameKey(db, record.nameKey.ascii).map((lead) => lead.id));
  }

  if (options.exactOnly !== true && record.cityId) {
    const block = findLeadsInCity(db, record.cityId);
    if (block.length > MAX_CITY_BLOCK) {
      options.onBlockTruncated?.(record.cityId, block.length);
    } else {
      collect(block.map((lead) => lead.id));
    }
  }

  const candidates: MatchCandidate[] = [];
  for (const leadId of candidateIds) {
    const other = toLeadRecord(db, leadId);
    if (!other) continue;
    const match = scoreMatch(record, other, { quarantine });
    if (match.decision === 'distinct' && options.includeDistinct !== true) continue;
    candidates.push({ leadId, lead: other, match });
  }

  return candidates.sort((a, b) => b.match.score - a.match.score || a.leadId - b.leadId);
}

/** `findCandidates` for a lead already stored. */
export function findCandidatesForLead(
  db: Db,
  leadId: number,
  options: FindCandidatesOptions = {},
): MatchCandidate[] {
  return findCandidates(db, requireLeadRecord(db, leadId), options);
}

/** One unordered pair the blocking found, scored once. */
export interface CandidatePair {
  readonly aId: number;
  readonly bId: number;
  readonly a: LeadRecord;
  readonly b: LeadRecord;
  readonly match: MatchScore;
}

/**
 * Every unordered pair the blocking finds across the whole database.
 *
 * This is what the sweep iterates. A pair reached from both ends is scored
 * once, and the pair is keyed on the smaller id first so it has one identity —
 * the same convention `merge_candidates` stores it under.
 */
export function allCandidatePairs(db: Db, options: FindCandidatesOptions = {}): CandidatePair[] {
  const seen = new Set<string>();
  const pairs: CandidatePair[] = [];
  for (const lead of activeLeads(db)) {
    const record = toLeadRecord(db, lead.id);
    if (!record) continue;
    for (const candidate of findCandidates(db, record, options)) {
      const [aId, bId] =
        lead.id < candidate.leadId ? [lead.id, candidate.leadId] : [candidate.leadId, lead.id];
      const key = `${aId}:${bId}`;
      if (seen.has(key)) continue;
      seen.add(key);
      const [a, b] = lead.id === aId ? [record, candidate.lead] : [candidate.lead, record];
      pairs.push({ aId, bId, a, b, match: candidate.match });
    }
  }
  return pairs.sort((x, y) => y.match.score - x.match.score || x.aId - y.aId || x.bId - y.bId);
}
